apiVersion: apps/v1
kind: Deployment
metadata:
  name: webecho
  namespace: cloudacademy
  labels:
    app: webecho
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webecho
      version: v1
  template:
    metadata:
      labels:
        app: webecho
        version: v1
    spec:
      containers:
      - name: webecho
        image: cloudacademydevops/webappecho:v4
        imagePullPolicy: IfNotPresent
        command: ["/go/bin/webapp"]
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: "OpenShift GitOps v1.1.3"
        - name: BACKGROUND_COLOR
          value: "yellow"
        - name: AUTO_RELOAD
          value: "20"